#!/bin/bash

# Script to fix mobile navigation across all lumi website files
# This script updates:
# 1. Logo: h-8 -ml-7 → h-6 md:h-8 md:-ml-7
# 2. Nav container: gap-8 → gap-4 md:gap-8
# 3. Nav links: text-lg → text-base md:text-lg

files=(
  "/src/app/components/BudgetCalculatorPage.tsx"
  "/src/app/components/BudgetingLesson10Page.tsx"
  "/src/app/components/BudgetingLesson11Page.tsx"
  "/src/app/components/BudgetingLesson12Page.tsx"
  "/src/app/components/BudgetingLesson1Page.tsx"
  "/src/app/components/BudgetingLesson2Page.tsx"
  "/src/app/components/BudgetingLesson3Page.tsx"
  "/src/app/components/BudgetingLesson4Page.tsx"
  "/src/app/components/BudgetingLesson5Page.tsx"
  "/src/app/components/BudgetingLesson6Page.tsx"
  "/src/app/components/BudgetingLesson7Page.tsx"
  "/src/app/components/BudgetingLesson8Page.tsx"
  "/src/app/components/BudgetingLesson9Page.tsx"
  "/src/app/components/CompoundGrowthVisualPage.tsx"
  "/src/app/components/ContactPage.tsx"
  "/src/app/components/CreditDebtLesson10Page.tsx"
  "/src/app/components/CreditDebtLesson11Page.tsx"
  "/src/app/components/CreditDebtLesson12Page.tsx"
  "/src/app/components/CreditDebtLesson1Page.tsx"
  "/src/app/components/CreditDebtLesson2Page.tsx"
  "/src/app/components/CreditDebtLesson3Page.tsx"
  "/src/app/components/CreditDebtLesson4Page.tsx"
  "/src/app/components/CreditDebtLesson5Page.tsx"
  "/src/app/components/CreditDebtLesson6Page.tsx"
  "/src/app/components/CreditDebtLesson7Page.tsx"
  "/src/app/components/CreditDebtLesson8Page.tsx"
  "/src/app/components/CreditDebtLesson9Page.tsx"
  "/src/app/components/CreditDebtPage.tsx"
  "/src/app/components/CreditScoreSimulatorPage.tsx"
  "/src/app/components/CustomerStoriesPage.tsx"
  "/src/app/components/DebtDecisionLabPage.tsx"
  "/src/app/components/FinancialPlanBuilderPage.tsx"
  "/src/app/components/FinancialPlanningLesson10Page.tsx"
  "/src/app/components/FinancialPlanningLesson11Page.tsx"
  "/src/app/components/FinancialPlanningLesson12Page.tsx"
  "/src/app/components/FinancialPlanningLesson1Page.tsx"
  "/src/app/components/FinancialPlanningLesson2Page.tsx"
  "/src/app/components/FinancialPlanningLesson3Page.tsx"
  "/src/app/components/FinancialPlanningLesson4Page.tsx"
  "/src/app/components/FinancialPlanningLesson5Page.tsx"
  "/src/app/components/FinancialPlanningLesson6Page.tsx"
  "/src/app/components/FinancialPlanningLesson7Page.tsx"
  "/src/app/components/FinancialPlanningLesson8Page.tsx"
  "/src/app/components/FinancialPlanningLesson9Page.tsx"
  "/src/app/components/FinancialPlanningPage.tsx"
  "/src/app/components/GetInvolvedPage.tsx"
  "/src/app/components/Investing101Page.tsx"
  "/src/app/components/InvestingLesson10Page.tsx"
  "/src/app/components/InvestingLesson1Page.tsx"
  "/src/app/components/InvestingLesson2Page.tsx"
  "/src/app/components/InvestingLesson3Page.tsx"
  "/src/app/components/InvestingLesson4Page.tsx"
  "/src/app/components/InvestingLesson5Page.tsx"
  "/src/app/components/InvestingLesson6Page.tsx"
  "/src/app/components/InvestingLesson7Page.tsx"
  "/src/app/components/InvestingLesson8Page.tsx"
  "/src/app/components/InvestingLesson9Page.tsx"
  "/src/app/components/InvestmentTypeExplorerPage.tsx"
  "/src/app/components/LiquidityArticlePage.tsx"
  "/src/app/components/PaycheckTaxEstimatorPage.tsx"
  "/src/app/components/PrivacyPolicyPage.tsx"
  "/src/app/components/SavingLesson10Page.tsx"
  "/src/app/components/SavingLesson1Page.tsx"
  "/src/app/components/SavingLesson2Page.tsx"
  "/src/app/components/SavingLesson3Page.tsx"
  "/src/app/components/SavingLesson4Page.tsx"
  "/src/app/components/SavingLesson5Page.tsx"
  "/src/app/components/SavingLesson6Page.tsx"
  "/src/app/components/SavingLesson7Page.tsx"
  "/src/app/components/SavingLesson8Page.tsx"
  "/src/app/components/SavingLesson9Page.tsx"
  "/src/app/components/SavingsStrategySelectorPage.tsx"
  "/src/app/components/TaxEssentialsLesson10Page.tsx"
  "/src/app/components/TaxEssentialsLesson11Page.tsx"
  "/src/app/components/TaxEssentialsLesson12Page.tsx"
  "/src/app/components/TaxEssentialsLesson1Page.tsx"
  "/src/app/components/TaxEssentialsLesson2Page.tsx"
  "/src/app/components/TaxEssentialsLesson3Page.tsx"
  "/src/app/components/TaxEssentialsLesson4Page.tsx"
  "/src/app/components/TaxEssentialsLesson5Page.tsx"
  "/src/app/components/TaxEssentialsLesson6Page.tsx"
  "/src/app/components/TaxEssentialsLesson7Page.tsx"
  "/src/app/components/TaxEssentialsLesson8Page.tsx"
  "/src/app/components/TaxEssentialsLesson9Page.tsx"
  "/src/app/components/TaxEssentialsPage.tsx"
  "/src/app/components/TradePolicyArticlePage.tsx"
  "/src/app/components/W4HelperPage.tsx"
  "/src/app/components/lessons/budgeting/BudgetingLesson8Page.tsx"
)

echo "Fixing mobile navigation in ${#files[@]} files..."
echo "Files to update list created successfully"
