import { useState, useEffect } from 'react';
import { Link } from './RouterLink';
import Footer from './Footer';
import lumiLogo from 'figma:asset/6faa24b9b39bf1a060318155560616649c074cb5.png';

interface PlanData {
  goalShort: string;
  goalMid: string;
  goalLong: string;
  topGoal: string;
  why: string;
  income: string;
  essentials: string;
  wants: string;
  savings: string;
  notesMap: string;
  emergencyTarget: string;
  autoSave: string;
  saveWhere: string;
  debt: string;
  debtStrategy: string;
  debtPayment: string;
  investReady: string;
  investVehicle: string;
  investRule: string;
  action1: string;
  action2: string;
  action3: string;
}

export default function FinancialPlanBuilderPage() {
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const initialData: PlanData = {
    goalShort: '',
    goalMid: '',
    goalLong: '',
    topGoal: 'short',
    why: '',
    income: '',
    essentials: '',
    wants: '',
    savings: '',
    notesMap: '',
    emergencyTarget: 'starter',
    autoSave: 'weekly',
    saveWhere: 'hysa',
    debt: 'none',
    debtStrategy: 'avalanche',
    debtPayment: '',
    investReady: 'notYet',
    investVehicle: 'index',
    investRule: '',
    action1: '',
    action2: '',
    action3: ''
  };

  const [data, setData] = useState<PlanData>(initialData);
  const [toast, setToast] = useState('');
  const [openSections, setOpenSections] = useState<{ [key: string]: boolean }>({
    goals: true,
    map: false,
    emergency: false,
    debt: false,
    invest: false,
    action: false
  });

  // Load from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem('lumi-financial-plan');
    if (saved) {
      try {
        setData(JSON.parse(saved));
      } catch (e) {
        console.error('Error loading saved plan:', e);
      }
    }
  }, []);

  // Auto-save to localStorage
  useEffect(() => {
    localStorage.setItem('lumi-financial-plan', JSON.stringify(data));
  }, [data]);

  const handleChange = (field: keyof PlanData, value: string) => {
    setData(prev => ({ ...prev, [field]: value }));
  };

  const countFilled = (fields: (keyof PlanData)[]) => {
    return fields.filter(f => data[f] && data[f].trim() !== '').length;
  };

  const goalsCount = countFilled(['goalShort', 'goalMid', 'goalLong', 'topGoal', 'why']);
  const mapCount = countFilled(['income', 'essentials', 'wants', 'savings', 'notesMap']);
  const emergencyCount = countFilled(['emergencyTarget', 'autoSave', 'saveWhere']);
  const debtCount = countFilled(['debt', 'debtStrategy', 'debtPayment']);
  const investCount = countFilled(['investReady', 'investVehicle', 'investRule']);
  const actionCount = countFilled(['action1', 'action2', 'action3']);

  const generatePlan = () => {
    let plan = '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    plan += 'MY FINANCIAL PLAN\n';
    plan += 'Generated by lumi Financial Plan Builder\n';
    plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n';

    // Goals
    plan += '1. MY GOALS\n';
    plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    if (data.goalShort) plan += `Short-term (0-6 months): ${data.goalShort}\n`;
    if (data.goalMid) plan += `Mid-term (6-24 months): ${data.goalMid}\n`;
    if (data.goalLong) plan += `Long-term (2+ years): ${data.goalLong}\n`;
    if (data.topGoal && data.why) {
      const priority = data.topGoal === 'short' ? 'Short-term' : data.topGoal === 'mid' ? 'Mid-term' : 'Long-term';
      plan += `\nTOP PRIORITY: ${priority}\n`;
      plan += `Why it matters: ${data.why}\n`;
    }
    plan += '\n';

    // Money Map
    plan += '2. MY MONTHLY MONEY MAP\n';
    plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    if (data.income) plan += `Monthly income: $${data.income}\n`;
    if (data.essentials) plan += `Essentials (needs): $${data.essentials}\n`;
    if (data.wants) plan += `Wants: $${data.wants}\n`;
    if (data.savings) plan += `Saving/Investing: $${data.savings}\n`;
    if (data.income && data.essentials && data.wants && data.savings) {
      const total = Number(data.essentials) + Number(data.wants) + Number(data.savings);
      const leftover = Number(data.income) - total;
      plan += `\nLeftover/Buffer: $${leftover}\n`;
    }
    if (data.notesMap) plan += `\nNotes: ${data.notesMap}\n`;
    plan += '\n';

    // Emergency Fund
    plan += '3. EMERGENCY FUND + SAVING PLAN\n';
    plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    const targetMap: { [key: string]: string } = {
      starter: 'Starter fund ($250-$500)',
      oneMonth: '1 month of essentials',
      threeMonths: '3 months of essentials'
    };
    if (data.emergencyTarget) plan += `Target: ${targetMap[data.emergencyTarget]}\n`;
    
    const autoSaveMap: { [key: string]: string } = {
      weekly: 'Weekly transfer',
      payday: 'Every payday transfer',
      monthly: 'Monthly transfer'
    };
    if (data.autoSave) plan += `Auto-save plan: ${autoSaveMap[data.autoSave]}\n`;
    
    const saveWhereMap: { [key: string]: string } = {
      hysa: 'High-yield savings account',
      savings: 'Regular savings account',
      cash: 'Cash envelope (small amounts only)'
    };
    if (data.saveWhere) plan += `Storage: ${saveWhereMap[data.saveWhere]}\n`;
    plan += '\n';

    // Debt
    if (data.debt !== 'none') {
      plan += '4. DEBT PLAN\n';
      plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
      const debtMap: { [key: string]: string } = {
        credit: 'Credit card balance',
        student: 'Student loan',
        other: 'Other debt'
      };
      if (data.debt) plan += `Type: ${debtMap[data.debt]}\n`;
      
      const strategyMap: { [key: string]: string } = {
        avalanche: 'Avalanche (highest interest first)',
        snowball: 'Snowball (smallest balance first)'
      };
      if (data.debtStrategy) plan += `Strategy: ${strategyMap[data.debtStrategy]}\n`;
      if (data.debtPayment) plan += `Monthly payment: $${data.debtPayment}\n`;
      plan += '\n';
    }

    // Investing
    plan += '5. INVESTING STARTER PLAN\n';
    plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    const readyMap: { [key: string]: string } = {
      notYet: 'Not yet (still building basics)',
      soon: 'Soon (next 1-3 months)',
      now: 'Yes (ready now)'
    };
    if (data.investReady) plan += `Readiness: ${readyMap[data.investReady]}\n`;
    
    const vehicleMap: { [key: string]: string } = {
      index: 'Low-cost index fund (long-term)',
      etf: 'ETF (similar to index funds)',
      roth: 'Roth IRA (if eligible and have earned income)',
      learn: 'Learning only for now'
    };
    if (data.investVehicle) plan += `Starter option: ${vehicleMap[data.investVehicle]}\n`;
    if (data.investRule) plan += `My rule: ${data.investRule}\n`;
    plan += '\n';

    // Actions
    plan += '6. MY NEXT 7 DAYS\n';
    plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    if (data.action1) plan += `□ ${data.action1}\n`;
    if (data.action2) plan += `□ ${data.action2}\n`;
    if (data.action3) plan += `□ ${data.action3}\n`;
    plan += '\n';

    plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    plan += 'Remember: A plan only works if you start.\n';
    plan += 'Small steps beat perfect plans.\n';
    plan += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';

    return plan;
  };

  const handleClear = () => {
    if (confirm('Are you sure you want to clear all fields? This cannot be undone.')) {
      setData(initialData);
      localStorage.removeItem('lumi-financial-plan');
      showToast('Plan cleared');
    }
  };

  const handleSave = () => {
    showToast('Plan saved to your device');
  };

  const handleCopy = async () => {
    const plan = generatePlan();
    try {
      await navigator.clipboard.writeText(plan);
      showToast('Plan copied to clipboard!');
    } catch (err) {
      showToast('Could not copy. Try selecting and copying manually.');
    }
  };

  const handlePrint = () => {
    const plan = generatePlan();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write('<html><head><title>My Financial Plan</title>');
      printWindow.document.write('<style>body{font-family:monospace;white-space:pre-wrap;padding:40px;line-height:1.6;}</style>');
      printWindow.document.write('</head><body>');
      printWindow.document.write(plan);
      printWindow.document.write('</body></html>');
      printWindow.document.close();
      printWindow.print();
    }
  };

  const showToast = (msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(''), 3000);
  };

  const toggleSection = (section: string) => {
    setOpenSections(prev => ({ ...prev, [section]: !prev[section] }));
  };

  const planOutput = generatePlan();

  return (
    <div className="min-h-screen bg-[#E5D7C4]">
      {/* Header */}
      <div className="sticky top-0 z-50 border-t-[16px] border-[#354024]">
        <header className="bg-[#889063] px-6 py-6 md:px-12">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <img src={lumiLogo} alt="lumi" className="h-8 -ml-7" style={{ mixBlendMode: 'multiply' }} />
            <nav className="flex gap-8">
              <Link to="/" className="text-lg text-[#1C1C1C] hover:opacity-70 transition-opacity">
                home
              </Link>
              <Link to="/learn" className="text-lg text-[#1C1C1C] hover:opacity-70 transition-opacity">
                learn
              </Link>
              <Link to="/resources" className="text-lg text-[#1C1C1C] hover:opacity-70 transition-opacity">
                resources
              </Link>
              <Link to="/blog" className="text-lg text-[#1C1C1C] hover:opacity-70 transition-opacity">
                blog
              </Link>
            </nav>
          </div>
        </header>
      </div>

      {/* Hero Section */}
      <div className="bg-[#354024] text-white px-6 py-16 md:py-20">
        <div className="max-w-5xl mx-auto text-center">
          <h1 className="text-5xl md:text-6xl text-[#FFCFD0] mb-6" style={{ letterSpacing: '-0.89px' }}>
            Financial Plan Builder
          </h1>
          <p className="text-xl md:text-2xl text-white opacity-90 max-w-3xl mx-auto leading-relaxed" style={{ letterSpacing: '-0.89px' }}>
            Build a simple plan you can actually follow. Fill out what you know, skip what you do not, and we will generate a one-page plan you can copy or print.
          </p>
        </div>
      </div>

      {/* Main Content */}
      <section className="px-6 py-16 md:px-12">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-[1fr_500px] gap-8">
            {/* Left: Builder */}
            <div className="bg-white rounded-2xl p-8 border-2 border-[#354024]">
              {/* Section 1: Goals */}
              <div className="mb-6 border-2 border-[#889063] rounded-xl bg-[#E5D7C4]/30">
                <button
                  onClick={() => toggleSection('goals')}
                  className="w-full px-6 py-4 flex items-center justify-between text-left"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  <span className="text-xl text-[#1C1C1C] font-semibold">1) Your goals</span>
                  <span className="text-sm px-3 py-1 rounded-full bg-[#889063] text-white border-2 border-[#354024]">
                    {goalsCount} filled
                  </span>
                </button>
                {openSections.goals && (
                  <div className="px-6 pb-6 pt-2 border-t-2 border-[#889063]">
                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Short-term goal (0 to 6 months)
                    </label>
                    <input
                      type="text"
                      value={data.goalShort}
                      onChange={(e) => handleChange('goalShort', e.target.value)}
                      placeholder="Example: Save $300 for an emergency fund starter"
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    />

                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Mid-term goal (6 to 24 months)
                    </label>
                    <input
                      type="text"
                      value={data.goalMid}
                      onChange={(e) => handleChange('goalMid', e.target.value)}
                      placeholder="Example: Save $1,500 for a laptop or car costs"
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    />

                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Long-term goal (2+ years)
                    </label>
                    <input
                      type="text"
                      value={data.goalLong}
                      onChange={(e) => handleChange('goalLong', e.target.value)}
                      placeholder="Example: Build investing habits and save for college"
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    />

                    <div className="grid md:grid-cols-2 gap-4 mt-4">
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Top priority goal right now
                        </label>
                        <select
                          value={data.topGoal}
                          onChange={(e) => handleChange('topGoal', e.target.value)}
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        >
                          <option value="short">Short-term</option>
                          <option value="mid">Mid-term</option>
                          <option value="long">Long-term</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Why does it matter?
                        </label>
                        <input
                          type="text"
                          value={data.why}
                          onChange={(e) => handleChange('why', e.target.value)}
                          placeholder="Example: I want to feel more secure"
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        />
                      </div>
                    </div>

                    <p className="text-sm text-[#1C1C1C] opacity-70 mt-4" style={{ letterSpacing: '-0.89px' }}>
                      A plan works best when you have one main goal you focus on first.
                    </p>
                  </div>
                )}
              </div>

              {/* Section 2: Money Map */}
              <div className="mb-6 border-2 border-[#889063] rounded-xl bg-[#E5D7C4]/30">
                <button
                  onClick={() => toggleSection('map')}
                  className="w-full px-6 py-4 flex items-center justify-between text-left"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  <span className="text-xl text-[#1C1C1C] font-semibold">2) Your monthly money map</span>
                  <span className="text-sm px-3 py-1 rounded-full bg-[#889063] text-white border-2 border-[#354024]">
                    {mapCount} filled
                  </span>
                </button>
                {openSections.map && (
                  <div className="px-6 pb-6 pt-2 border-t-2 border-[#889063]">
                    <div className="grid md:grid-cols-2 gap-4 mt-4">
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Monthly income (after tax if you know it)
                        </label>
                        <input
                          type="number"
                          value={data.income}
                          onChange={(e) => handleChange('income', e.target.value)}
                          placeholder="Example: 900"
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Monthly essentials (needs)
                        </label>
                        <input
                          type="number"
                          value={data.essentials}
                          onChange={(e) => handleChange('essentials', e.target.value)}
                          placeholder="Example: 250"
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        />
                      </div>
                    </div>

                    <div className="grid md:grid-cols-2 gap-4 mt-4">
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Monthly wants
                        </label>
                        <input
                          type="number"
                          value={data.wants}
                          onChange={(e) => handleChange('wants', e.target.value)}
                          placeholder="Example: 150"
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Monthly saving/investing
                        </label>
                        <input
                          type="number"
                          value={data.savings}
                          onChange={(e) => handleChange('savings', e.target.value)}
                          placeholder="Example: 200"
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        />
                      </div>
                    </div>

                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Notes (optional)
                    </label>
                    <textarea
                      value={data.notesMap}
                      onChange={(e) => handleChange('notesMap', e.target.value)}
                      placeholder="Example: My income changes because of shifts. I want to keep wants under $30/week."
                      rows={3}
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    />

                    <p className="text-sm text-[#1C1C1C] opacity-70 mt-4" style={{ letterSpacing: '-0.89px' }}>
                      If the numbers do not add up perfectly, that is okay. This is a starting map.
                    </p>
                  </div>
                )}
              </div>

              {/* Section 3: Emergency Fund */}
              <div className="mb-6 border-2 border-[#889063] rounded-xl bg-[#E5D7C4]/30">
                <button
                  onClick={() => toggleSection('emergency')}
                  className="w-full px-6 py-4 flex items-center justify-between text-left"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  <span className="text-xl text-[#1C1C1C] font-semibold">3) Emergency fund + saving plan</span>
                  <span className="text-sm px-3 py-1 rounded-full bg-[#889063] text-white border-2 border-[#354024]">
                    {emergencyCount} filled
                  </span>
                </button>
                {openSections.emergency && (
                  <div className="px-6 pb-6 pt-2 border-t-2 border-[#889063]">
                    <div className="grid md:grid-cols-2 gap-4 mt-4">
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Emergency fund target
                        </label>
                        <select
                          value={data.emergencyTarget}
                          onChange={(e) => handleChange('emergencyTarget', e.target.value)}
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        >
                          <option value="starter">Starter fund ($250 to $500)</option>
                          <option value="oneMonth">1 month of essentials</option>
                          <option value="threeMonths">3 months of essentials</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Auto-save plan
                        </label>
                        <select
                          value={data.autoSave}
                          onChange={(e) => handleChange('autoSave', e.target.value)}
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        >
                          <option value="weekly">Weekly transfer</option>
                          <option value="payday">Every payday transfer</option>
                          <option value="monthly">Monthly transfer</option>
                        </select>
                      </div>
                    </div>

                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Where will you store savings?
                    </label>
                    <select
                      value={data.saveWhere}
                      onChange={(e) => handleChange('saveWhere', e.target.value)}
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    >
                      <option value="hysa">High-yield savings account</option>
                      <option value="savings">Regular savings account</option>
                      <option value="cash">Cash envelope (small amounts only)</option>
                    </select>

                    <p className="text-sm text-[#1C1C1C] opacity-70 mt-4" style={{ letterSpacing: '-0.89px' }}>
                      Emergency fund = boring on purpose. It should be safe and easy to access.
                    </p>
                  </div>
                )}
              </div>

              {/* Section 4: Debt */}
              <div className="mb-6 border-2 border-[#889063] rounded-xl bg-[#E5D7C4]/30">
                <button
                  onClick={() => toggleSection('debt')}
                  className="w-full px-6 py-4 flex items-center justify-between text-left"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  <span className="text-xl text-[#1C1C1C] font-semibold">4) Debt plan (if you have any)</span>
                  <span className="text-sm px-3 py-1 rounded-full bg-[#889063] text-white border-2 border-[#354024]">
                    {debtCount} filled
                  </span>
                </button>
                {openSections.debt && (
                  <div className="px-6 pb-6 pt-2 border-t-2 border-[#889063]">
                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Do you have debt you are paying?
                    </label>
                    <select
                      value={data.debt}
                      onChange={(e) => handleChange('debt', e.target.value)}
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    >
                      <option value="none">No debt</option>
                      <option value="credit">Credit card balance</option>
                      <option value="student">Student loan</option>
                      <option value="other">Other</option>
                    </select>

                    <div className="grid md:grid-cols-2 gap-4 mt-4">
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Strategy
                        </label>
                        <select
                          value={data.debtStrategy}
                          onChange={(e) => handleChange('debtStrategy', e.target.value)}
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        >
                          <option value="avalanche">Avalanche (highest interest first)</option>
                          <option value="snowball">Snowball (smallest balance first)</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-semibold text-[#1C1C1C] mb-2" style={{ letterSpacing: '-0.89px' }}>
                          Monthly debt payment (if any)
                        </label>
                        <input
                          type="number"
                          value={data.debtPayment}
                          onChange={(e) => handleChange('debtPayment', e.target.value)}
                          placeholder="Example: 50"
                          className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                          style={{ letterSpacing: '-0.89px' }}
                        />
                      </div>
                    </div>

                    <p className="text-sm text-[#1C1C1C] opacity-70 mt-4" style={{ letterSpacing: '-0.89px' }}>
                      If you have debt, the plan is usually: emergency starter fund first, then pay debt aggressively.
                    </p>
                  </div>
                )}
              </div>

              {/* Section 5: Investing */}
              <div className="mb-6 border-2 border-[#889063] rounded-xl bg-[#E5D7C4]/30">
                <button
                  onClick={() => toggleSection('invest')}
                  className="w-full px-6 py-4 flex items-center justify-between text-left"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  <span className="text-xl text-[#1C1C1C] font-semibold">5) Investing starter plan</span>
                  <span className="text-sm px-3 py-1 rounded-full bg-[#889063] text-white border-2 border-[#354024]">
                    {investCount} filled
                  </span>
                </button>
                {openSections.invest && (
                  <div className="px-6 pb-6 pt-2 border-t-2 border-[#889063]">
                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Are you ready to invest right now?
                    </label>
                    <select
                      value={data.investReady}
                      onChange={(e) => handleChange('investReady', e.target.value)}
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    >
                      <option value="notYet">Not yet (still building basics)</option>
                      <option value="soon">Soon (next 1 to 3 months)</option>
                      <option value="now">Yes (ready now)</option>
                    </select>

                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Starter option (educational)
                    </label>
                    <select
                      value={data.investVehicle}
                      onChange={(e) => handleChange('investVehicle', e.target.value)}
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    >
                      <option value="index">Low-cost index fund (long-term)</option>
                      <option value="etf">ETF (similar to index funds)</option>
                      <option value="roth">Roth IRA (if eligible and have earned income)</option>
                      <option value="learn">Learning only for now</option>
                    </select>

                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Your simple rule
                    </label>
                    <input
                      type="text"
                      value={data.investRule}
                      onChange={(e) => handleChange('investRule', e.target.value)}
                      placeholder="Example: Invest 10% of income after emergency fund starter is done"
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    />

                    <p className="text-sm text-[#1C1C1C] opacity-70 mt-4" style={{ letterSpacing: '-0.89px' }}>
                      Investing is a long game. You do not need to be perfect, you need to be consistent.
                    </p>
                  </div>
                )}
              </div>

              {/* Section 6: Actions */}
              <div className="mb-6 border-2 border-[#889063] rounded-xl bg-[#E5D7C4]/30">
                <button
                  onClick={() => toggleSection('action')}
                  className="w-full px-6 py-4 flex items-center justify-between text-left"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  <span className="text-xl text-[#1C1C1C] font-semibold">6) Your next 7 days</span>
                  <span className="text-sm px-3 py-1 rounded-full bg-[#889063] text-white border-2 border-[#354024]">
                    {actionCount} filled
                  </span>
                </button>
                {openSections.action && (
                  <div className="px-6 pb-6 pt-2 border-t-2 border-[#889063]">
                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Action step 1
                    </label>
                    <input
                      type="text"
                      value={data.action1}
                      onChange={(e) => handleChange('action1', e.target.value)}
                      placeholder="Example: Open a separate savings account for emergency fund"
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    />

                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Action step 2
                    </label>
                    <input
                      type="text"
                      value={data.action2}
                      onChange={(e) => handleChange('action2', e.target.value)}
                      placeholder="Example: Set up an auto-transfer every payday"
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    />

                    <label className="block text-sm font-semibold text-[#1C1C1C] mt-4 mb-2" style={{ letterSpacing: '-0.89px' }}>
                      Action step 3
                    </label>
                    <input
                      type="text"
                      value={data.action3}
                      onChange={(e) => handleChange('action3', e.target.value)}
                      placeholder="Example: Track spending for 7 days to find leaks"
                      className="w-full px-4 py-3 border-2 border-[#889063] rounded-xl text-[#1C1C1C]"
                      style={{ letterSpacing: '-0.89px' }}
                    />

                    <p className="text-sm text-[#1C1C1C] opacity-70 mt-4" style={{ letterSpacing: '-0.89px' }}>
                      Small steps that actually happen beat perfect plans that never start.
                    </p>
                  </div>
                )}
              </div>

              {/* Action Buttons */}
              <div className="flex flex-wrap gap-3 mb-4">
                <button
                  onClick={handleClear}
                  className="px-6 py-3 bg-[#E5D7C4] border-2 border-[#889063] rounded-xl text-[#1C1C1C] font-semibold hover:opacity-80 transition-opacity"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  Clear
                </button>
                <button
                  onClick={handleSave}
                  className="px-6 py-3 bg-white border-2 border-[#354024] rounded-xl text-[#1C1C1C] font-semibold hover:opacity-80 transition-opacity"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  Save
                </button>
                <button
                  onClick={handleCopy}
                  className="px-6 py-3 bg-[#354024] border-2 border-[#354024] rounded-xl text-white font-semibold hover:opacity-90 transition-opacity"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  Copy plan
                </button>
                <button
                  onClick={handlePrint}
                  className="px-6 py-3 bg-white border-2 border-[#354024] rounded-xl text-[#1C1C1C] font-semibold hover:opacity-80 transition-opacity"
                  style={{ letterSpacing: '-0.89px' }}
                >
                  Print
                </button>
              </div>

              {toast && (
                <div className="mt-4 px-4 py-3 bg-[#889063]/20 border-2 border-[#889063] rounded-xl text-[#1C1C1C]" style={{ letterSpacing: '-0.89px' }}>
                  {toast}
                </div>
              )}

              <p className="text-sm text-[#1C1C1C] opacity-70 mt-4" style={{ letterSpacing: '-0.89px' }}>
                Educational tool. Not financial advice. If you are under 18, use a parent or guardian for accounts and legal decisions.
              </p>
            </div>

            {/* Right: Output */}
            <div className="bg-white rounded-2xl p-8 border-2 border-[#354024] lg:sticky lg:top-32 h-fit">
              <h2 className="text-3xl text-[#354024] mb-3 font-semibold" style={{ letterSpacing: '-0.89px' }}>
                Your one-page plan
              </h2>
              <div className="inline-block px-3 py-1 rounded-full bg-[#889063] text-white text-sm mb-4 border-2 border-[#354024]">
                Auto-saves on your device
              </div>
              <div className="bg-[#E5D7C4]/30 border-2 border-[#889063] rounded-xl p-6 font-mono text-sm whitespace-pre-wrap text-[#1C1C1C] leading-relaxed overflow-y-auto max-h-[600px]">
                {planOutput}
              </div>
              <p className="text-sm text-[#1C1C1C] opacity-70 mt-4" style={{ letterSpacing: '-0.89px' }}>
                Tip: you can copy this into Notes, Google Docs, or print it and stick it on your wall.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Bottom Navigation */}
      <div className="border-t-2 border-[#354024] bg-[#889063] px-6 py-8 md:px-12">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <Link
            to="/resources"
            onClick={scrollToTop}
            className="text-lg text-[#1C1C1C] hover:opacity-70 transition-opacity"
            style={{ letterSpacing: '-0.89px' }}
          >
            ← Back to Resources
          </Link>
          <Link
            to="/w4-helper"
            onClick={scrollToTop}
            className="text-lg text-[#1C1C1C] hover:opacity-70 transition-opacity"
            style={{ letterSpacing: '-0.89px' }}
          >
            W-4 Helper →
          </Link>
        </div>
      </div>

      <Footer />
    </div>
  );
}
